sudo: required
services:
- docker
env:
  global:
    - IMAGE_NAME=zdays/sistem-users
    - secure: "VsJd1ITbnQYtfAq96V0Rh+PWX79wylHUkMP4Q0mpbRQEbOWHa41BqvNQxFjynRSiGrtp7PkNNStDjANi1kSd5P/gO8nHdNN9UMrbL600S3jqJVFbhF3C6sUa64OX7sRjjO3Riw9Xal28tF+8PrgssLuZ18i8kropaL4NUEaYR7g1zAdbOXl+Vt0LDYR/pYaLKsLAHqMuRH0ZPDafxJOd7OJHe/+NQ8vw9zSWvtQTE2YSysJYTa310IFD0dGr+Ll1kUZHJhPOUawdDn91V4LaIBsoM8iqYDUAI7aIVhmMqu3UOTYgNm8xOJBiakGHbvWhICkegBiBaWrhQBEc/ylL/J8qXVMzCGCTSRiI9Uh1mrJCONfTT77C2+WFfwXpkSwWLXdK/MztuTT3pOuUyohdPt92+nn3Lm+XTmg5FPip7Ar39mwOdho5nndl0qb+HZ0P222l8Qpc9+NfvVxhf3TmIwro3aobwF0GTijJmRaibuW87uqOmGaFzR66UksJ9kLInsihvM3OuymCP+2fbvMFklWcl39oeG9QAq03HgVmMh8NJAkMXN50M6OlqkNByzyTG2Wp6tGdidooMKgEdIzchbaqMGT6p/FboKpN3spsbDD7LRXq8qCLjQ0x+ux5T6UxTQ898gJjP4squMHOcCAK0xlOrgeYtFatzaPm38BosiQ="
    - secure: "MkK0nXjgyjq6hq9U8XVislWe7NDUWL4Tx5TqV5C/SQar/77U55iDhvj3rXVVIor+Pg5oPqBmXamuju/z6qyJez4GRgrCEO8+D3DBuAVvS94V3tx5Py5Gh0Zqpa2HSJFAEDiTiw1eW0983AdAaJ0xlC/sw5UAjNYYihPZS2EfFZMul9CY7UY7XHgoQfs6bpvDMiRAJIhLtplWgM2K94uKyJJkArvrouafsiEvlymd5npKAMwb9IcWalf/1Y5sTwsyoXk6/Qjc2seRFjRfp8NuRPDEky1TsnykM17tBSKE9H1CV9FUWgkuIUlrg+H9rObVPiuqd1dB8Ao98SIGGws/2380vEzSrMkX9ioQAk3qhjmtJspYaN3yt+ifCwZXCfuqKeIAkIxI7dgZqF1VTjYqikEAwCMVtJwcHlRe0UROb+ScfngTyYcD7nVJ7crXOonP9eiWDjFvTrjzMv35WlrSUOixt3gnSHWY+pQsm/BwabZmFdRneXP3nYn1r0YFgC5tQGLvkvC2cR0WAtK7L++YiSx3ygYNBU3lB0UapkiQPRBTq2Q3QlQax8JPhdZTBF5LjxUYg7JyGt14yx5nSnbEHieBt4h6ZOZ/9HrExTRFmiSy9LcRK636bu0TJqfzYfIpjewhi8c3Jix+8LUqYpI3sJMxRV8AnSKrIb6xfEL3Wj0="
script:
  - docker build -t "$IMAGE_NAME" .

before_deploy:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${TRAVIS_JOB_NUMBER}"

deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${TRAVIS_JOB_NUMBER}"
