sudo: required
services:
- docker
env:
  global:
    - IMAGE_NAME=zdays/sistem-users
    - secure: "VsJd1ITbnQYtfAq96V0Rh+PWX79wylHUkMP4Q0mpbRQEbOWHa41BqvNQxFjynRSiGrtp7PkNNStDjANi1kSd5P/gO8nHdNN9UMrbL600S3jqJVFbhF3C6sUa64OX7sRjjO3Riw9Xal28tF+8PrgssLuZ18i8kropaL4NUEaYR7g1zAdbOXl+Vt0LDYR/pYaLKsLAHqMuRH0ZPDafxJOd7OJHe/+NQ8vw9zSWvtQTE2YSysJYTa310IFD0dGr+Ll1kUZHJhPOUawdDn91V4LaIBsoM8iqYDUAI7aIVhmMqu3UOTYgNm8xOJBiakGHbvWhICkegBiBaWrhQBEc/ylL/J8qXVMzCGCTSRiI9Uh1mrJCONfTT77C2+WFfwXpkSwWLXdK/MztuTT3pOuUyohdPt92+nn3Lm+XTmg5FPip7Ar39mwOdho5nndl0qb+HZ0P222l8Qpc9+NfvVxhf3TmIwro3aobwF0GTijJmRaibuW87uqOmGaFzR66UksJ9kLInsihvM3OuymCP+2fbvMFklWcl39oeG9QAq03HgVmMh8NJAkMXN50M6OlqkNByzyTG2Wp6tGdidooMKgEdIzchbaqMGT6p/FboKpN3spsbDD7LRXq8qCLjQ0x+ux5T6UxTQ898gJjP4squMHOcCAK0xlOrgeYtFatzaPm38BosiQ="
    - secure: "VFJlQZHZ9prVjuQLMtLQgiTsm3jVzdnOtcYoncySjp/F9SSaPci+JFb/TNQcue8TnFtC7ZThhgeLPEjkLaMjE7VHY72KXIycYQSMjo87TVhJJKHsQB0AqJbDYJ18wiQogMCyTrlodguGEWGzYu0I1xpdU5v97J4RmpgYENTPMPC4aRJrTGcO4iRDbeVFEgcCf35ZZrzgeeawBj+Ze2ziOlepYn62G51Ccfir00Dw574Usy6WQR0NUYuvJ48jy/1Y8IZw3VbSG8KtJtE9713aKuWDOOAYurIEYSN7eWnQkGLn3WQq4Rkz7Cb+79Tuuz/G1Yo6CXVOZK7YrgP0zVwCMFkXWzcOVGK6CPoYV4/b/OVVVydX5Ni2qscRVP2mRglzkLmsdoXHK/BCtTXTkWGPUPnbLtc2CHAnYCD6TQJTAV7LP36f97PVdQRFnZNXabKnlj11GBQCN4De+2yRD2/RNhcO6sq1am29QtNqOnwizRznmQNrzpx5B0zDsS/gKXKz158gUVrhi/F62xPnz9HS966L9TXm6QxCf0XW7p4Pqk6tUD+JgqJmiIQRiUvQMSWRe/S7qELoxLDgw4ezUyaLSPoh0yrnLtio6oRXZB9pzZ0z2qcSWZszrqrwG/K/gDqWobwa23HlpjF0B7XbjK7kLQDaLjvQqrv9jLH3sH16QGQ="
script:
  - docker build -t "$IMAGE_NAME" .

before_deploy:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${TRAVIS_JOB_NUMBER}"

deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${TRAVIS_JOB_NUMBER}"
