apiVersion: apps/v1
kind: Deployment
metadata:
  name: sistem-users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sistem-users
  template:
    metadata:
      labels:
        app: sistem-users
    spec:
      containers:
        - image: zdays/sistem-users:latest
          name: sistem-users
          env:
            - name: SISTEM_USERS_DATABASE_HOST
              value: db.recompile.it
            - name: SISTEM_USERS_DATABASE_DB_NAME
              value: sistem_users
            - name: SISTEM_USERS_DATABASE_SSL_MODE
              value: require
            - name: SISTEM_USERS_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: sistem-db
                  key: username
            - name: SISTEM_USERS_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sistem-db
                  key: password
            - name: SISTEM_USERS_LOGIN_SIGNING_PRIVATE_KEY_LOCATION
              value: "/app/keys/privkey.pem"
            - name: SISTEM_USERS_LOGIN_SIGNING_PUBLIC_KEY_LOCATION
              value: "/app/keys/pubkey.pem"
            # TODO env
          volumeMounts:
            - name: keys
              mountPath: "/app/keys"
              readOnly: true
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP
      volumes:
        - name: keys
          secret:
            secretName: user-keys

---

apiVersion: v1
kind: Service
metadata:
  name: sistem-users
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: sistem-users
