apiVersion: apps/v1
kind: Deployment
metadata:
  name: sistem-users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sistem-users
  template:
    metadata:
      labels:
        app: sistem-users
    spec:
      containers:
        - image: zdays/sistem-users:latest
          name: sistem-users
          env:
            - name: SISTEM_USERS_DATABASE_HOST
              value: 123.123.123.123
            # TODO env
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: sistem-users
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: sistem-users
